/* Generated by Together */

package net.soft_systems.crypto.beans.policy;
import java.util.*;
import net.soft_systems.crypto.Run;
import net.soft_systems.crypto.event.SystemChangeListener;
import net.soft_systems.integrator.*;
public class CommandGroupBean extends TopicBean implements ParentDynamicBean {
	protected SystemChangeListener systemChangeListener;
	public CommandGroupBean() {
		super("commands", "Множество команд");
		systemChangeListener = new SystemChangeListener() {
			public void elementsChanged(Vector subjects, Vector resources)
				{ validateElements(subjects, resources); }
			public void rightsChanged(Vector availRights) { validateRights(availRights); }
		};
		Run.infoSystem.addSystemChangeListener(systemChangeListener);
	}
	public String getChildName() { return "Команда"; }
	public Class getChildClass() { return CommandBean.class; }
	public void validateElements(Vector subjects, Vector resources) {
		Enumeration en = getChildBeans().elements();
		CommandBean obj;
		while (en.hasMoreElements()) {
			obj = (CommandBean)en.nextElement();
			obj.validateElements(subjects, resources);
		}
	}
	public void validateRights(Vector availRights) {
		Enumeration en = getChildBeans().elements();
		CommandBean obj;
		while (en.hasMoreElements()) {
			obj = (CommandBean)en.nextElement();
			obj.validateRights(availRights);
		}
	}
	public void finalize() throws Throwable {
		Run.infoSystem.removeSystemChangeListener(systemChangeListener);
		super.finalize();
	}
}

