/* Generated by Together */

package net.soft_systems.crypto.beans.policy;
import net.soft_systems.integrator.TopicBean;
public class PolicyGroupBean extends TopicBean {
	public PolicyGroupBean() { super("policies", "Политика безопасности"); }
}

