/* Generated by Together */

package net.soft_systems.crypto.beans.policy;
import net.soft_systems.integrator.*;
public class RightGroupBean extends TopicBean implements ParentDynamicBean {
	public RightGroupBean() { super("rights", "Множество прав доступа"); }
	public String getChildName() { return "Право доступа"; }
	public Class getChildClass() { return RightBean.class; }
}

