/* Generated by Together */

package net.soft_systems.crypto.frames;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import net.soft_systems.crypto.Run;
import net.soft_systems.integrator.*;
public class ElementsPanel extends JPanel implements UpdatablePanel {
	protected ParentDynamicBean parentBean;
	public Bean getParentBean() { return parentBean; }
	protected void init() {
		listPanel = new JPanel();
		buttonPanel = new JPanel();
		listName = new JLabel();
		list = new JList();
		addButton = new JButton();
		editButton = new JButton();
		delButton = new JButton();
		JScrollPane scrollListPane = new JScrollPane(list);
		//setting text values
		listName.setText(Run.integrator.messages.getMessage("elem-list"));
		editButton.setText(Run.integrator.messages.getMessage("edit"));
		addButton.setText(Run.integrator.messages.getMessage("add"));
		delButton.setText(Run.integrator.messages.getMessage("del"));
		// adding ui elements
		setLayout(new GridBagLayout());
		add(listPanel,
			new GridBagConstraints(0, 0, 1, GridBagConstraints.REMAINDER, 1.0, 1.0, GridBagConstraints.SOUTHWEST,
			GridBagConstraints.BOTH, new Insets(0, 0, 0, 0), 0, 0));
		add(buttonPanel,
			new GridBagConstraints(1, 0, 1, 1, 0.0, 1.0, GridBagConstraints.EAST, GridBagConstraints.BOTH,
			new Insets(0, 0, 0, 0), 0, 0));
		setBounds(new Rectangle(0, 0, 379, 446));
		listPanel.setLayout(new GridBagLayout());
		listPanel.add(listName,
			new GridBagConstraints(0, 0, GridBagConstraints.REMAINDER, GridBagConstraints.RELATIVE, 1.0, 0.0,
			GridBagConstraints.SOUTH, GridBagConstraints.HORIZONTAL, new Insets(5, 5, 0, 5), 0, 0));
		listPanel.add(scrollListPane,
			new GridBagConstraints(0, GridBagConstraints.RELATIVE, GridBagConstraints.REMAINDER,
			GridBagConstraints.REMAINDER, 1.0, 1.0, GridBagConstraints.CENTER, GridBagConstraints.BOTH,
			new Insets(5, 5, 5, 5), 0, 0));
		buttonPanel.setLayout(new GridBagLayout());
		buttonPanel.add(addButton,
			new GridBagConstraints(0, 0, GridBagConstraints.REMAINDER, 1, 1.0, 0.0, GridBagConstraints.SOUTH,
			GridBagConstraints.HORIZONTAL, new Insets(5, 5, 0, 5), 0, 0));
		buttonPanel.add(editButton,
			new GridBagConstraints(0, 1, GridBagConstraints.REMAINDER, 1, 1.0, 0.0, GridBagConstraints.SOUTH,
			GridBagConstraints.HORIZONTAL, new Insets(5, 5, 0, 5), 0, 0));
		buttonPanel.add(delButton,
			new GridBagConstraints(0, 2, GridBagConstraints.REMAINDER, 1, 1.0, 0.0, GridBagConstraints.CENTER,
			GridBagConstraints.HORIZONTAL, new Insets(5, 5, 0, 5), 0, 0));
		list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		// adding ActionListeners to buttons
		addButton.addActionListener(
			new ActionListener() {
				public void actionPerformed(ActionEvent e) { doAddElement(); }
			});
		delButton.addActionListener(
			new ActionListener() {
				public void actionPerformed(ActionEvent e) { doDelElement(); }
			});
		editButton.addActionListener(
			new ActionListener() {
				public void actionPerformed(ActionEvent e) { doEditElement(); }
			});
		list.addMouseListener(
			new MouseAdapter() {
				public void mouseClicked(MouseEvent e) {
					if (e.getClickCount() > 1) { doEditElement(); }
				}
			});
	}
	protected void doAddElement() {
		Bean newBean = Run.integrator.addBean(parentBean.getChildClass(), parentBean, true);
		list.setListData(parentBean.getChildBeans());
		list.setSelectedValue(newBean, true);
	}
	protected void doEditElement() {
		if (list.getSelectedIndex() >= 0 && list.getSelectedIndex() < parentBean.getChildBeans().size()) {
			Bean bean = (Bean)list.getSelectedValue();
			if (bean != null) { Run.integrator.tryEditBean(bean); }
		}
	}
	protected void doDelElement() {
		if (list.getSelectedIndex() >= 0 && list.getSelectedIndex() < parentBean.getChildBeans().size()) {
			Bean bean = (Bean)list.getSelectedValue();
			if (bean != null) {
				Run.integrator.delBean(bean, parentBean, true);
				list.repaint();
			}
		}
	}
	public void update() { list.setListData(this.parentBean.getChildBeans()); }
	public ElementsPanel(ParentDynamicBean parentBean) {
		super();
		this.parentBean = parentBean;
		init();
		list.setListData(parentBean.getChildBeans());
	}
	private JPanel listPanel;
	private JLabel listName;
	private JPanel buttonPanel;
	private JList list;
	private JButton addButton;
	private JButton editButton;
	private JButton delButton;
}

