/* Generated by Together */

package net.soft_systems.crypto.frames;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.TitledBorder;
public class JDialog1 extends JDialog {
	/**
	 * ------------------------------------------------------------------------------------------------------
	 * Creates new form JDialog -----------------------------------------------------------------------------------------------------
	 */
	public JDialog1(Frame parent, boolean modal) {
		super(parent, modal);
		initGUI();
	}
	/**
	 * ------------------------------------------------------------------------------------------------------
	 * This method is called from within the constructor to initialize the form.
	 * ----------------------------------------------------------------------------------------------------
	 */
	private void initGUI() {
		GridBagConstraints gridBagConstraints1;
		gridBagConstraints1 = new GridBagConstraints();
		gridBagConstraints1.gridwidth = GridBagConstraints.REMAINDER;
		gridBagConstraints1.gridheight = 1;
		gridBagConstraints1.fill = GridBagConstraints.BOTH;
		gridBagConstraints1.weightx = 100;
		gridBagConstraints1.insets = new Insets(0, 5, 0, 10);
		gridBagConstraints1 = new GridBagConstraints();
		gridBagConstraints1.gridwidth = GridBagConstraints.REMAINDER;
		gridBagConstraints1.gridheight = 1;
		gridBagConstraints1.fill = GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.weightx = 1;
		gridBagConstraints1.weighty = 1;
		gridBagConstraints1.insets = new Insets(5, 5, 5, 5);
		gridBagConstraints1.anchor = GridBagConstraints.NORTH;
		addWindowListener(
			new WindowAdapter() {
				public void windowClosing(WindowEvent evt) { closeDialog(evt); }
			});
		pack();
		setBounds(new Rectangle(0, 0, 517, 335));
		GridBagLayout layout = new GridBagLayout();
		layout = new GridBagLayout();
		getContentPane().setLayout(layout);
		getContentPane().add(modelsPanel,
			new GridBagConstraints(0, 0, GridBagConstraints.REMAINDER, GridBagConstraints.REMAINDER, 0.0, 0.0,
			GridBagConstraints.CENTER, GridBagConstraints.BOTH, new Insets(5, 5, 5, 5), 0, 0));
		getContentPane().add(buttonPanel,
			new GridBagConstraints(GridBagConstraints.RELATIVE, GridBagConstraints.RELATIVE, 1, 1, 0.0, 0.0,
			GridBagConstraints.CENTER, GridBagConstraints.NONE, new Insets(0, 0, 0, 0), 0, 0));
		modelsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(153, 153, 153), 1),
			"Модели безопасности", TitledBorder.LEADING, TitledBorder.TOP, new Font("SansSerif", 0, 11),
			new Color(60, 60, 60)));
		modelsPanel.add(jPanel2);
	}
	/**
	 * ------------------------------------------------------------------------------------------------------
	 * Closes the dialog -----------------------------------------------------------------------------------------------------
	 */
	private void closeDialog(WindowEvent evt) {
		setVisible(false);
		dispose();
	}
	private JPanel modelsPanel = new JPanel();
	private JPanel jPanel2     = new JPanel();
	private JPanel buttonPanel = new JPanel();
}

