/* Generated by Together */

package net.soft_systems.crypto.beans;
import net.soft_systems.integrator.TopicBean;
public class ConfigGroupBean extends TopicBean {
	public ConfigGroupBean() { super("config", "Настройки среды"); }
}

