/* Generated by Together */

package net.soft_systems.crypto.beans.process;
import net.soft_systems.integrator.*;
public class MethodGroupBean extends TopicBean implements ParentDynamicBean {
	static public MethodGroupBean createWithStandartMethods() {
		MethodGroupBean group = new MethodGroupBean();
		group.addBean(new MethodBean("onCreate"));
		group.addBean(new MethodBean("onDestroy"));
		group.addBean(new MethodBean("onRecieve"));
		return group;
	}
	public MethodGroupBean() { super("methods", "Ìועמהû ןנמצוססא"); }
	public String getChildName() { return "Ìועמה"; }
	public Class getChildClass() { return MethodBean.class; }
}

