/* Generated by Together */

package net.soft_systems.crypto.beans.process;
import net.soft_systems.integrator.*;
public class NodeGroupBean extends TopicBean implements ParentDynamicBean {
	public NodeGroupBean() { super("nodes", "Узлы процесса"); }
	public String getChildName() { return "Узел"; }
	public Class getChildClass() { return NodeBean.class; }
}

