/* Generated by Together */

package net.soft_systems.crypto.ui;
import java.text.*;
import java.util.Date;
public class Formats {
	static DecimalFormat decimalFormat;
	static public NumberFormat getDecimalFormat() {
		if (decimalFormat == null) {
			decimalFormat = new DecimalFormat();
			decimalFormat.setGroupingSize(3);
			decimalFormat.setMaximumFractionDigits(6);
		}
		return decimalFormat;
	}
	static public String format(double value) { return getDecimalFormat().format(value); }
	static DateFormat dateFormat;
	static public DateFormat getDateFormat() {
		if (dateFormat == null) { dateFormat = new SimpleDateFormat("hh:mm:ss dd.MM"); }
		return dateFormat;
	}
	static public String format(Date value) { return getDateFormat().format(value); }
}

