/* Generated by Together */

package net.soft_systems.crypto.frames.structure;
import net.soft_systems.crypto.Run;
import net.soft_systems.crypto.frames.ElementsPanel;
import net.soft_systems.integrator.*;
public class SubjectsPanel extends ElementsPanel {
	public SubjectsPanel() { super((ParentDynamicBean)BeanUtil.getBeanById(Run.rootBean, "subjects")); }
}

