/* Generated by Together */

package net.soft_systems.crypto.frames.structure;
import java.awt.*;
import net.soft_systems.crypto.base.CryptoBean;
import net.soft_systems.crypto.frames.*;
public class SubjectEditFrame extends CryptoEditFrame {
	public SubjectEditFrame(CryptoBean bean) { super(bean); }
	private RelationPanel relationsPanel;
	protected void initRelationsPanel() { relationsPanel = new RelationPanel(this); }
	protected void doOk() {
		setId();
		relationsPanel.setRelations();
		closeFrame();
	}
	protected void init() {
		this.setSize(400, 500);
		initPropertiesPanel();
		GridBagLayout layout = new GridBagLayout();
		getContentPane().setLayout(layout);
		GridBagConstraints c = new GridBagConstraints();
		c.gridwidth = GridBagConstraints.REMAINDER;
		c.gridheight = 1;
		c.fill = GridBagConstraints.HORIZONTAL;
		c.weightx = 1;
		c.weighty = 1;
		c.insets = new Insets(5, 5, 5, 5);
		c.anchor = GridBagConstraints.NORTH;
		getContentPane().add(propertiesPanel, c);
		initRelationsPanel();
		getContentPane().add(relationsPanel,
			new GridBagConstraints(GridBagConstraints.RELATIVE, GridBagConstraints.RELATIVE,
			GridBagConstraints.REMAINDER, GridBagConstraints.RELATIVE, 1.0, 100.0, GridBagConstraints.NORTH,
			GridBagConstraints.BOTH, new Insets(0, 5, 5, 5), 0, 0));
		initButtonPanel();
		c = new GridBagConstraints();
		c.gridwidth = GridBagConstraints.REMAINDER;
		c.gridheight = 1;
		c.fill = GridBagConstraints.HORIZONTAL;
		c.weightx = 1;
		c.weighty = 0;
		c.insets = new Insets(0, 0, 0, 0);
		c.anchor = GridBagConstraints.SOUTH;
		getContentPane().add(buttonPanel, c);
	}
}

