/* Generated by Together */

package net.soft_systems.crypto.frames.structure;
import net.soft_systems.crypto.Run;
import net.soft_systems.crypto.frames.ViewElementsPanel;
import net.soft_systems.integrator.BeanUtil;
public class VulnerabilitiesPanel extends ViewElementsPanel {
	public VulnerabilitiesPanel() { super(BeanUtil.getBeanById(Run.rootBean, "vulnerabilities")); }
}

