/* Generated by Together */

package net.soft_systems.crypto.beans.structure;
import net.soft_systems.integrator.TopicBean;
public class StructureGroupBean extends TopicBean {
	public StructureGroupBean() { super("structure", "Статическая модель"); }
}

