/* Generated by Together */

package net.soft_systems.integrator;
public interface BaseNameEnabled extends Bean {
	/**
	 * @return start of identifier. It is concatenated with number of element which is not used.
	 */
	String getBaseName();
}

