/* Generated by Together */

package net.soft_systems.integrator;
import java.text.SimpleDateFormat;
import java.util.Date;
public class Debug {
	public final static int DEBUG    = 0;
	public final static int NOTICE   = 1;
	public final static int WARNING  = 2;
	public final static int ERROR    = 3;
	public final static int CRITICAL = 4;
	static protected String getMessageStart(int type) {
		String msg;
		switch (type) {
			case NOTICE:
				msg = "Сообщение: ";
			break;
			case DEBUG:
				msg = "Отладка: ";
			break;
			case WARNING:
				msg = "Предупреждение: ";
			break;
			case ERROR:
				msg = "Ошибка: ";
			break;
			case CRITICAL:
				msg = "Критическая ошибка: ";
			break;
			default:
				msg = "Отладка: ";
			break;
		}
		SimpleDateFormat f = new SimpleDateFormat("dd.MM hh:mm:ss");
		return f.format(new Date()) + " " + msg;
	}
	public static void message(String msg, int type) {
		Integrator.addMessage(getMessageStart(type) + msg + "\n");
		// System.err.println(getMessageStart(type) + msg);
	}
	public static void notice(String message) { message(message, NOTICE); }
	public static void debug(String message) {
		//message(message, DEBUG);
	}
	public static void warning(String message) { message(message, WARNING); }
	public static void error(String message) { message(message, ERROR); }
	public static void critical(String message) { message(message, CRITICAL); }
}

