/* Generated by Together */

package net.soft_systems.integrator;
import java.io.*;
import java.util.*;
import net.soft_systems.routines.Config;
/**
 * ----------------------------------------------------------------------------------------------------------
 * Messages represents class holding user interface localisezed messages
 * --------------------------------------------------------------------------------------------------------
 */
public class Messages {
	public static String BASENAME = "ui";
	private ResourceBundle messages;
	public Messages() {
		try {
			messages = new PropertyResourceBundle(
				new FileInputStream(Config.getConfigDir() + File.separator + BASENAME + "_" +
				Locale.getDefault().toString() + ".properties"));
		}
		catch (Exception ex) {
			try {
				messages = new PropertyResourceBundle(
					new FileInputStream(Config.getConfigDir() + File.separator + BASENAME + ".properties"));
			}
			catch (Exception ex1) {
				try {
					messages = new PropertyResourceBundle(
						new FileInputStream(Config.getDefaultDir() + File.separator + BASENAME + "_" +
						Locale.getDefault().toString() + ".properties"));
				}
				catch (Exception ex_1) {
					try {
						messages = new PropertyResourceBundle(
							new FileInputStream(Config.getDefaultDir() + File.separator + BASENAME + ".properties"));
					}
					catch (Exception ex2) { ex2.printStackTrace(); }
				}
			}
		}
	}
	public String getMessage(String key) { return messages.getString(key); }
}

