/* Generated by Together */

package net.soft_systems.integrator;
import java.util.Vector;
public interface RelationEnabledBean extends Bean {
	Vector getAccessedObjects();
	Vector getAvailObjects();
	void setAccessedObjects(Vector objects);
	String getAvailObjectsName();
	String getAccessedObjectsName();
	String getRelationInfo();
}

