--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CORPS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		CORPS VARCHAR(30) DEFAULT '' NOT NULL,
		AUDIENCE VARCHAR(30) DEFAULT '',
		FURNITURE VARCHAR(30) DEFAULT ''
	);

CREATE UNIQUE INDEX SQL211016172513850 ON CORPS (ID ASC);

ALTER TABLE CORPS ADD CONSTRAINT SQL211016172513850 PRIMARY KEY (ID);

