/* Generated by Together */

package net.soft_systems.integrator.event;
import javax.swing.JMenuBar;
public interface InitMenuListener {
	/**
	 * ------------------------------------------------------------------------------------------------------
	 * Can add menus to menubar
	 * @param menu Menu object. It must not be changed. Adding submenus is allowed only.
	 * ----------------------------------------------------------------------------------------------------
	 */
	void init(JMenuBar menu);
}

