/* Generated by Together */

package net.soft_systems.crypto.frames.policy;
import net.soft_systems.integrator.*;
public class PolicyFrame extends EditFrame {
	public PolicyFrame(Bean bean) { super(bean); }
}

