/* Generated by Together */

package net.soft_systems.crypto.base;
import net.soft_systems.integrator.*;
import org.w3c.dom.Element;
abstract public class CryptoRenderableBean extends CryptoBean implements RenderableBean {
	public CryptoRenderableBean() { super(); }
	public CryptoRenderableBean(String id) { super(id); }
	public double getX() { return x; }
	public Sign getSign() { return null; }
	public double getY() { return y; }
	public void moveTo(double x, double y) {
		if (x > 0) { this.x = x; }
		else { x = 0; }
		if (y > 0) { this.y = y; }
		else { y = 0; }
	}
	/**
	 * Saves bean configuration to xml storage
	 * @param beanElement Element which encapsulates configuration of the bean
	 * @param config Object which provides functions to set element data
	 */
	public void store(Element beanElement, BeanConfig config) {
		super.store(beanElement, config);
		config.setAttribute(beanElement, "x", "" + getX());
		config.setAttribute(beanElement, "y", "" + getY());
	}
	/**
	 * Loads bean configuration from xml element
	 * @param beanElement Element which encapsulates configuration of the bean
	 * @param config Object which provides functions to get data from element
	 */
	public void load(Element beanElement, BeanConfig config) {
		super.load(beanElement, config);
		moveTo(config.getDoubleAttribute(beanElement, "x", 0), config.getDoubleAttribute(beanElement, "y", 0));
	}
	private double y;
	private double x;
}

