/* Generated by Together */

package net.soft_systems.crypto.base;
import java.util.Vector;
import net.soft_systems.integrator.*;
public class ProcessSystemHolder extends PolicySystemHolder {
	protected ProcessSystemHolder() { super(); }
	static public ProcessSystemHolder getNewProcessSystemHolder(Bean rootBean) {
		ProcessSystemHolder sh = new ProcessSystemHolder();
		sh.init(rootBean);
		return sh;
	}
	public void init(Bean rootBean) {
		super.init(rootBean);
		if (rootBean != null) {
			try {
				processes = BeanUtil.getBeanById(rootBean, "processes").getChildBeans();
				channels = BeanUtil.getBeanById(rootBean, "channels").getChildBeans();
			}
			catch (NullPointerException ex) { Debug.critical("Ошибка в иерархии элементов"); }
		}
		else { Debug.critical("Ошибка в иерархии элементов"); }
	}
	public Vector getProcesses() { return processes; }
	public Vector getChannels() { return channels; }
	private Vector processes;
	private Vector channels;
	public Bean getChannelTopic() { return BeanUtil.getBeanById(rootBean, "channels"); }
}

